[package]
name = "rayoff"
version = "0.1.0"
edition = "2024"
description = "Feature-gate Rayon usage in a Rust project"

[dependencies]
rayon = { version = "1.11.0", optional = true }

[features]
rayon = ["dep:rayon"]
